//! Exodus Browser — Microservice Infrastructure
//! 
//! This module provides the foundation for a microservice architecture using
//! Unix Domain Sockets (UDS) and JSON-RPC 2.0 for inter-process communication.

pub mod protocol;
pub mod bus;
pub mod registry;
pub mod supervisor;
pub mod log_collector;
pub mod resource_monitor;
pub mod rag_service;
pub mod rag_commands;
pub mod crypto_service;
pub mod crypto_commands;
pub mod os_service;
pub mod os_commands;
pub mod p2p_blobs_service;
pub mod p2p_gossip_service;
pub mod gossip_client;
pub mod p2p_commands;
pub mod ai_model_service;
pub mod ai_model_commands;
pub mod file_transfer_service;
pub mod file_transfer_commands;
pub mod file_transfer_hub;
pub mod ai_agent_service;
pub mod ai_agent_commands;
pub mod contact_directory_service;
pub mod contact_directory_hub;
pub mod contact_directory_commands;
pub mod group_chat_service;
pub mod group_chat_client;
pub mod group_chat_commands;
pub mod social_feed_service;
pub mod social_feed_commands;
pub mod agent_discovery_service;
pub mod agent_discovery_commands;
pub mod media_streaming_service;
pub mod media_streaming_commands;
pub mod news_aggregation_service;
pub mod news_aggregation_commands;
pub mod public_account_service;
pub mod public_account_commands;
pub mod service_exposure_service;
pub mod service_exposure_commands;
pub mod port_forwarding_service;
pub mod port_forwarding_commands;
pub mod video_communication_service;
pub mod video_communication_commands;
pub mod collaborative_editing_service;
pub mod collaborative_editing_commands;
pub mod clipboard_sync_service;
pub mod clipboard_sync_commands;
pub mod terminal_session_service;
pub mod chat_storage;
pub mod message_resend;
pub mod group_assistant;
pub mod p2p_group_coordinator;
pub mod terminal_session_commands;
pub mod ai_video_analysis_service;
pub mod ai_video_analysis_commands;
pub mod circuit_breaker;
pub mod service_discovery;
pub mod distributed_tracing;
pub mod config_manager;
pub mod metrics;
pub mod allama_process;
pub mod allama_http_client;
pub mod allama_gateway;
pub mod allama_service;
pub mod allama_commands;
pub mod resilience;

pub use bus::MicroserviceBus;
pub use registry::{ServiceRegistry, ServiceInfo, ServiceStatus};
pub use supervisor::ServiceSupervisor;
pub use rag_service::{RagService, RagServiceConfig};
pub use crypto_service::{CryptoService, CryptoServiceConfig, extract_12_digit_from_hex, format_12_digit_with_hyphens};
pub use os_service::{OsService, OsServiceConfig};
pub use p2p_blobs_service::{P2pBlobsService, P2pBlobsConfig, BlobTicket};
pub use p2p_gossip_service::{P2pGossipService, P2pGossipConfig, GossipMessage};
pub use ai_model_service::{AiModelService, AiModelServiceConfig, AiModelMetadata, ModelRegistration, ModelSearchQuery};
pub use file_transfer_service::{FileTransferService, FileTransferServiceConfig, FileTransferMetadata, FileChunk};
pub use ai_agent_service::{AiAgentService, AiAgentServiceConfig, AgentIdentity, AgentMessage, AgentPresence};
pub use contact_directory_service::{ContactDirectoryService, ContactDirectoryServiceConfig, Contact, ContactGroup};
pub use group_chat_service::{GroupChatService, GroupChatServiceConfig, GroupChat, GroupMessage, GroupMember, GroupInvitation, DirectChat, DirectMessage, MessageReceipt, UserSequence, GroupSequence};
pub use chat_storage::{ChatStorage, ChatStorageConfig, Friend, DirectMessage as StoredDirectMessage, GroupMessage as StoredGroupMessage, MessageAttachment as StoredAttachment, MessageReceipt as StoredReceipt};
pub use message_resend::{MessageResendService, ResendRequest, ResendResponse, ResentMessage};
pub use group_assistant::{GroupAssistantService, GroupAssistantConfig, GroupAssistant, AssistantMessage};
pub use p2p_group_coordinator::{P2PGroupCoordinator, MessageSourcePriority, RetrievalStrategy, MissingMessageRequest, RetrievalResult, RetrievedMessage, P2PMessageService, CloudAssistantService, P2PMessage, CloudMessage};
pub use social_feed_service::{SocialFeedService, SocialFeedServiceConfig, SocialPost, SocialComment, SocialReaction};
pub use agent_discovery_service::{AgentDiscoveryService, AgentDiscoveryServiceConfig, DiscoveryCriteria, AgentRecommendation, TrendingAgent};
pub use media_streaming_service::{MediaStreamingService, MediaStreamingServiceConfig, StreamSession, StreamViewer, StreamQuality, AudioQuality, AudioEffects, AudioAnalysis, AudioMixerConfig};
pub use news_aggregation_service::{NewsAggregationService, NewsAggregationServiceConfig, NewsArticle, NewsSource, NewsFeedConfig, NewsStats};
pub use public_account_service::{PublicAccountService, PublicAccountServiceConfig, PublicAccount, Article, Follower, ArticleAnalytics, AccountAnalytics, MediaItem, CustomMenuItem, PushNotification};
pub use service_exposure_service::{ServiceExposureService, ServiceExposureServiceConfig, ServiceExposureConfig, ServiceExposureMetadata};
pub use port_forwarding_service::{PortForwardingService, PortForwardingServiceConfig, PortForwardingConfig, PortForwardingMetadata};
pub use video_communication_service::{VideoCommunicationService, VideoCommunicationServiceConfig, VideoCallConfig, VideoCallMetadata, VideoFrame, AudioFrame};
pub use collaborative_editing_service::{CollaborativeEditingService, CollaborativeEditingServiceConfig, DocumentConfig, DocumentMetadata, TextOperation, CursorPosition};
pub use clipboard_sync_service::{ClipboardSyncService, ClipboardSyncServiceConfig, ClipboardSyncConfig, ClipboardSyncMetadata, ClipboardItem};
pub use terminal_session_service::{TerminalSessionService, TerminalSessionServiceConfig, TerminalSessionConfig, TerminalSessionMetadata, TerminalOutput};
pub use ai_video_analysis_service::{AiVideoAnalysisService, AiVideoAnalysisServiceConfig, AnalysisTask, DetectionResult, AnalysisStats};
pub use circuit_breaker::{CircuitBreaker, CircuitBreakerConfig, CircuitState, CircuitBreakerStats};
pub use service_discovery::{ServiceDiscovery, ServiceEndpoint, ServiceDiscoveryStats};
pub use distributed_tracing::{TracingCollector, TraceContext, Span, Trace, SpanStatus, LogLevel};
pub use config_manager::{ConfigManager, ConfigEntry, ConfigChangeEvent, ConfigStats};
pub use metrics::{MetricsCollector, MetricType, MetricValue, Metric, Histogram, MetricsStats};
pub use allama_service::{AllamaService, AllamaServiceConfig, AllamaServiceStatus, AllamaRuntimeMode};
pub use allama_process::ALLAMA_DEFAULT_PORT;
pub use allama_http_client::{AllamaHttpClient, ChatMessage as AllamaChatMessage, default_allama_base_url};
pub use resilience::{RetryConfig, RetryPolicy, ResilientHttpClient, HealthMonitor, HealthStatus, HealthCheck, retry_with_backoff, Fallback, DegradationManager, DegradationLevel, DegradationThresholds};
